require_relative '../app/models/ranking'

describe Ranking do
  file = File.read('data.txt')
  mock_data = JSON.parse(file)['results']
  let(:subject) { Class.new { extend Ranking}}


  it 'returns an array of all the materials used' do
    expect(subject.all_objects mock_data, 'materials').to eq( ["agate", "Tibetan silver", "Vintage Silk Kimono Obi", "gold", "black", "card", "memory", "a special cotton texture", "Chain", "Hoop Frame", "Fabric", "Wood", "Recycled", "Brooch pin", "Parrot clasp", "40s Black Cameo locket", "lightweight polyester", "wall art", "home decor", "waxed yarn from Thailand", "cowry shell", "brass beads", "howlite beads", "coconut button", "yak", "wool", "blended fabric", "paper", "ink", "acrylic yarn", "organic catnip", "polyesterfiberfill", "citrine", "gold", "Canson 140 lb white watercolor paper", "pro paint", "illustrator", "photoshop", "paper", "digital download", "jpg", "png", "vector art", "eps", "925 Sterling Silver", "gold clasp", "copper", "fabric", "cotton", "wool blend", "cotton blend with spandex", "925 Sterling Silver", "CUBIC ZIRCONIA", "14K Gold Filled"] )
  end

  it 'turns the array into a hash with key, value pairs' do
    expect(subject.map_to_hash ["agate", "Tibetan silver", "Vintage Silk Kimono Obi", "gold", "black", "card", "memory", "a special cotton texture", "Chain", "Hoop Frame", "Fabric", "Wood", "Recycled", "Brooch pin", "Parrot clasp", "40s Black Cameo locket", "lightweight polyester", "wall art", "home decor", "waxed yarn from Thailand", "cowry shell", "brass beads", "howlite beads", "coconut button", "yak", "wool", "blended fabric", "paper", "ink", "acrylic yarn", "organic catnip", "polyesterfiberfill", "citrine", "gold", "Canson 140 lb white watercolor paper", "pro paint", "illustrator", "photoshop", "paper", "digital download", "jpg", "png", "vector art", "eps", "925 Sterling Silver", "gold clasp", "copper", "fabric", "cotton", "wool blend", "cotton blend with spandex", "925 Sterling Silver", "CUBIC ZIRCONIA", "14K Gold Filled"] ).to eq({"agate"=>1, "Tibetan silver"=>1, "Vintage Silk Kimono Obi"=>1, "gold"=>2, "black"=>1, "card"=>1, "memory"=>1, "a special cotton texture"=>1, "Chain"=>1, "Hoop Frame"=>1, "Fabric"=>1, "Wood"=>1, "Recycled"=>1, "Brooch pin"=>1, "Parrot clasp"=>1, "40s Black Cameo locket"=>1, "lightweight polyester"=>1, "wall art"=>1, "home decor"=>1, "waxed yarn from Thailand"=>1, "cowry shell"=>1, "brass beads"=>1, "howlite beads"=>1, "coconut button"=>1, "yak"=>1, "wool"=>1, "blended fabric"=>1, "paper"=>2, "ink"=>1, "acrylic yarn"=>1, "organic catnip"=>1, "polyesterfiberfill"=>1, "citrine"=>1, "Canson 140 lb white watercolor paper"=>1, "pro paint"=>1, "illustrator"=>1, "photoshop"=>1, "digital download"=>1, "jpg"=>1, "png"=>1, "vector art"=>1, "eps"=>1, "925 Sterling Silver"=>2, "gold clasp"=>1, "copper"=>1, "fabric"=>1, "cotton"=>1, "wool blend"=>1, "cotton blend with spandex"=>1, "CUBIC ZIRCONIA"=>1, "14K Gold Filled"=>1})
  end

  it 'sorts the hash by most common occurence' do
    expect(subject.sort_by_occurence({"agate"=>1, "Tibetan silver"=>1, "Vintage Silk Kimono Obi"=>1, "gold"=>2, "black"=>1, "card"=>1, "memory"=>1, "a special cotton texture"=>1, "Chain"=>1, "Hoop Frame"=>1, "Fabric"=>1, "Wood"=>1, "Recycled"=>1, "Brooch pin"=>1, "Parrot clasp"=>1, "40s Black Cameo locket"=>1, "lightweight polyester"=>1, "wall art"=>1, "home decor"=>1, "waxed yarn from Thailand"=>1, "cowry shell"=>1, "brass beads"=>1, "howlite beads"=>1, "coconut button"=>1, "yak"=>1, "wool"=>1, "blended fabric"=>1, "paper"=>2, "ink"=>1, "acrylic yarn"=>1, "organic catnip"=>1, "polyesterfiberfill"=>1, "citrine"=>1, "Canson 140 lb white watercolor paper"=>1, "pro paint"=>1, "illustrator"=>1, "photoshop"=>1, "digital download"=>1, "jpg"=>1, "png"=>1, "vector art"=>1, "eps"=>1, "925 Sterling Silver"=>2, "gold clasp"=>1, "copper"=>1, "fabric"=>1, "cotton"=>1, "wool blend"=>1, "cotton blend with spandex"=>1, "CUBIC ZIRCONIA"=>1, "14K Gold Filled"=>1})).to eq ([["gold", 2], ["paper", 2], ["925 Sterling Silver", 2], ["wool", 1], ["cotton", 1], ["fabric", 1], ["copper", 1], ["gold clasp", 1], ["cotton blend with spandex", 1], ["eps", 1], ["vector art", 1], ["png", 1], ["jpg", 1], ["digital download", 1], ["photoshop", 1], ["illustrator", 1], ["pro paint", 1], ["Canson 140 lb white watercolor paper", 1], ["citrine", 1], ["polyesterfiberfill", 1], ["organic catnip", 1], ["acrylic yarn", 1], ["ink", 1], ["CUBIC ZIRCONIA", 1], ["blended fabric", 1], ["wool blend", 1], ["yak", 1], ["coconut button", 1], ["howlite beads", 1], ["brass beads", 1], ["cowry shell", 1], ["waxed yarn from Thailand", 1], ["home decor", 1], ["wall art", 1], ["lightweight polyester", 1], ["40s Black Cameo locket", 1], ["Parrot clasp", 1], ["Brooch pin", 1], ["Recycled", 1], ["Wood", 1], ["Fabric", 1], ["Hoop Frame", 1], ["Chain", 1], ["a special cotton texture", 1], ["memory", 1], ["card", 1], ["black", 1], ["14K Gold Filled", 1], ["Vintage Silk Kimono Obi", 1], ["Tibetan silver", 1], ["agate", 1]])
  end

  it 'removes all of the the items that have occured once' do
    expect(subject.remove_occurences([["gold", 2], ["paper", 2], ["925 Sterling Silver", 2], ["wool", 1], ["cotton", 1], ["fabric", 1], ["copper", 1], ["gold clasp", 1], ["cotton blend with spandex", 1], ["eps", 1], ["vector art", 1], ["png", 1], ["jpg", 1], ["digital download", 1], ["photoshop", 1], ["illustrator", 1], ["pro paint", 1], ["Canson 140 lb white watercolor paper", 1], ["citrine", 1], ["polyesterfiberfill", 1], ["organic catnip", 1], ["acrylic yarn", 1], ["ink", 1], ["CUBIC ZIRCONIA", 1], ["blended fabric", 1], ["wool blend", 1], ["yak", 1], ["coconut button", 1], ["howlite beads", 1], ["brass beads", 1], ["cowry shell", 1], ["waxed yarn from Thailand", 1], ["home decor", 1], ["wall art", 1], ["lightweight polyester", 1], ["40s Black Cameo locket", 1], ["Parrot clasp", 1], ["Brooch pin", 1], ["Recycled", 1], ["Wood", 1], ["Fabric", 1], ["Hoop Frame", 1], ["Chain", 1], ["a special cotton texture", 1], ["memory", 1], ["card", 1], ["black", 1], ["14K Gold Filled", 1], ["Vintage Silk Kimono Obi", 1], ["Tibetan silver", 1], ["agate", 1]])).to eq([["gold", 2], ["paper", 2], ["925 Sterling Silver", 2]])
  end

  it 'creates an array with the most popular objects' do
    expect(subject.most_popular ([["gold", 2], ["paper", 2], ["925 Sterling Silver", 2]])).to eq ["gold", "paper", "925 Sterling Silver"]
  end

  it 'creates an array with the titles of the most popular objects' do
    expect(subject.most_popular_items mock_data, 'materials', ["gold", "paper", "925 Sterling Silver"]).to eq (["Harlow Collection - Sample Pack", "Bob Marley Daschund Print Poster Illustration Acrylic Painting Animal Portrait  Decor Wall Hanging Wall Art Drawing Glicee Digital", "Vintage Citrine Cluster Ring in 9K Yellow Gold. 4 Round Cut. Unique Engagement Ring. November Birthstone. 13th Anniversary.  Estate Jewelry.", "Instant Download Vintage Digital Flourish Border Frame Clip Art Scrapbooking Embellishment Frame Clipart Frame Decor Design Elements 0146", "New 925 Sterling Silver Barrel Clasp Bracelet with gold clasp standard Bracelet Chain Snake charm Bracelet -  for European Charms and Beads", "NEW Twinkle Twinkle Safety Chain 925 Sterling Silver with Clear CZ Safety Chain Stopper Beads Fits European style Bracelet For Women SA007"])
  end

end
